"""se añade columna cedula

Revision ID: 999e1364adaa
Revises: 2a71f0e75146
Create Date: 2026-03-14 13:12:31.412921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '999e1364adaa'
down_revision = '2a71f0e75146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cedula', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('cedula')

    # ### end Alembic commands ###
