"""modifica nombre de columna telefono a movil

Revision ID: edd0daa4d2d0
Revises: 999e1364adaa
Create Date: 2026-03-14 14:33:37.279501

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'edd0daa4d2d0'
down_revision = '999e1364adaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movil', sa.String(length=20), nullable=True))
        batch_op.drop_column('telefono')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefono', mysql.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('movil')

    # ### end Alembic commands ###
