"""se quita algunas columnas para que queden en orden

Revision ID: f2f7d704eec5
Revises: edd0daa4d2d0
Create Date: 2026-03-14 14:35:32.592601

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f2f7d704eec5'
down_revision = 'edd0daa4d2d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('correo'))
        batch_op.drop_column('movil')
        batch_op.drop_column('nombre')
        batch_op.drop_column('apellido')
        batch_op.drop_column('correo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correo', mysql.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('apellido', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('nombre', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('movil', mysql.VARCHAR(length=20), nullable=True))
        batch_op.create_index(batch_op.f('correo'), ['correo'], unique=True)

    # ### end Alembic commands ###
